// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* 1) onnxruntime-web 라이브러리 먼저 */}
        <Script
          id="ort-lib"
          src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.0/dist/ort.min.js"
          strategy="afterInteractive"
        />

        {/* 2) ORT 전역 설정: 파일별 '절대 URL' 매핑 + 보수 옵션 */}
        <Script
          id="ort-config"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(){
                var BASE='https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.0/dist/';
                var ABS={
                  'ort-wasm.wasm':               BASE+'ort-wasm.wasm',
                  'ort-wasm-simd.wasm':          BASE+'ort-wasm-simd.wasm',
                  'ort-wasm-threaded.wasm':      BASE+'ort-wasm-threaded.wasm',
                  'ort-wasm-simd-threaded.wasm': BASE+'ort-wasm-simd-threaded.wasm',
                };
                globalThis.ort=globalThis.ort||{};
                globalThis.ort.env=globalThis.ort.env||{};
                globalThis.ort.env.wasm=Object.assign(globalThis.ort.env.wasm||{},{
                  wasmPaths: ABS,              // ★ 파일별 절대 URL 매핑
                  proxy: false,
                  numThreads: 1,
                  simd: false,
                  fetchOptions: { mode: 'cors', credentials: 'omit' },
                });
                console.log('[ORT configured]', globalThis.ort.env.wasm);
              })();
            `,
          }}
        />

        {/* 3) transformers ESM 로드 + 전역에 고정 + onnx 보수 옵션 */}
        <Script
          id="transformers-loader"
          type="module"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (async () => {
                if (!globalThis.transformers) {
                  const m = await import('https://cdn.jsdelivr.net/npm/@xenova/transformers@latest/dist/transformers.min.js');
                  const mod = m?.pipeline ? m : (m?.default?.pipeline ? m.default : null);
                  if (!mod) throw new Error('transformers loaded but pipeline not found');

                  // transformers 쪽 env도 onnx 보수 설정으로 맞춤
                  const env = mod.env;
                  env.allowRemoteModels = true;
                  env.useBrowserCache   = true;

                  env.backends = env.backends || {};
                  env.backends.onnx  = env.backends.onnx  || { enabled: true };
                  env.backends.webgpu = { enabled: false };
                  env.backends.webnn  = { enabled: false };
                  env.backends.tfjs   = { enabled: false };
                  env.backends.tflite = { enabled: false };

                  env.backends.onnx.wasm = Object.assign(env.backends.onnx.wasm||{}, {
                    wasmPaths: globalThis.ort?.env?.wasm?.wasmPaths, // ABS 매핑 재사용
                    proxy: false,
                    numThreads: 1,
                    simd: false,
                    fetchOptions: { mode: 'cors', credentials: 'omit' },
                  });

                  globalThis.transformers = mod;
                  console.log('[transformers ready]');
                }
              })().catch(e => console.error('[transformers import error]', e));
            `,
          }}
        />
      </body>
    </html>
  );
}